services:
  mysql:
    image: mysql:8.0.42
    container_name: abdulib-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: 123123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mounting the init-scripts directory

volumes:
  mysql-data:
